FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/frontend/package*.json ./apps/frontend/

RUN npm install --workspaces --include-workspace-root --no-audit --no-fund

COPY . .

WORKDIR /app/apps/frontend
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]