# apps/frontend/dockerfile.frontend
FROM node:22-alpine

WORKDIR /app

# Solo el package del frontend
COPY apps/frontend/package*.json ./

# Instalar deps del frontend
RUN npm install --no-audit --no-fund

# Copiar el código del frontend al contenedor
COPY apps/frontend ./

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--strictPort"]
